"""add seo columns to posts

Revision ID: 8a12a74f2b9d
Revises: d30edcbc3b4a
Create Date: 2026-07-06 21:27:56.180091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a12a74f2b9d'
down_revision: Union[str, Sequence[str], None] = 'd30edcbc3b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('meta_title', sa.String(length=70), nullable=True))
    op.add_column('posts', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('posts', sa.Column('canonical_url', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('robots', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('og_image_url', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('focus_keyword', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'focus_keyword')
    op.drop_column('posts', 'og_image_url')
    op.drop_column('posts', 'robots')
    op.drop_column('posts', 'canonical_url')
    op.drop_column('posts', 'meta_description')
    op.drop_column('posts', 'meta_title')
    # ### end Alembic commands ###
